# Generated by Django 5.0.6 on 2025-02-17 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('release_data', models.DateField()),
                ('duration_mins', models.FloatField()),
                ('rating', models.FloatField(default=-1)),
                ('rating_quantity', models.IntegerField(default=0)),
                ('poster_url', models.CharField(max_length=2048)),
                ('trailer_url', models.CharField(max_length=2048)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField(default=1)),
                ('random', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieEntry',
            fields=[
                ('movie_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.genre')),
                ('movie_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkEntry',
            fields=[
                ('bookmark_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_entry_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.user')),
            ],
        ),
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('watch_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('watch_percentage', models.FloatField(default=0)),
                ('updated_at', models.DateField()),
                ('movie_entry_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.user')),
            ],
        ),
    ]
