# Generated by Django 5.0.6 on 2025-03-13 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=512)),
                ('middle_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('poster_url', models.CharField(max_length=2048)),
                ('movie_file_url', models.CharField(max_length=2048)),
                ('age_restriction', models.IntegerField(default=1)),
                ('release_date', models.DateField()),
                ('duration_seconds', models.IntegerField()),
                ('created_at', models.DateField()),
                ('activated_at', models.DateField()),
                ('modified_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkEntry',
            fields=[
                ('bookmark_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActorEntry',
            fields=[
                ('movie_genre_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.actor')),
                ('movie_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenreEntry',
            fields=[
                ('movie_genre_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.genre')),
                ('movie_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieStatistics',
            fields=[
                ('movie_stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=-1)),
                ('rating_count', models.IntegerField(default=0)),
                ('views_overall', models.IntegerField(default=0)),
                ('views_daily', models.IntegerField(default=0)),
                ('views_weekly', models.IntegerField(default=0)),
                ('views_monthly', models.IntegerField(default=0)),
                ('views_annually', models.IntegerField(default=0)),
                ('movie_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
            ],
        ),
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('watch_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('watch_progress', models.FloatField(default=0)),
                ('updated_at', models.DateField()),
                ('movie_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
