# Generated by Django 5.0.6 on 2025-02-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='random',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
