# Generated by Django 5.0.6 on 2025-03-13 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_site', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingEntry',
            fields=[
                ('rating_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.FloatField(default=-1)),
                ('movie_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_site.movie')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
