# Generated by Django 5.1.7 on 2025-04-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_site', '0002_ratingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_duration_seconds',
            field=models.IntegerField(default=1),
        ),
    ]
