# Generated by Django 5.0.6 on 2025-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_site', '0003_genre_movie_user_movieentry_bookmarkentry_watchentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkentry',
            name='bookmark_entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movieentry',
            name='movie_entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchentry',
            name='watch_entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
