# Generated by Django 5.0.6 on 2025-03-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=256)),
                ('all_meeting_text', models.TextField()),
                ('arnav_present', models.BooleanField(default=True)),
                ('kayden_present', models.BooleanField(default=True)),
                ('ian_present', models.BooleanField(default=True)),
                ('keon_present', models.BooleanField(default=True)),
                ('bao_present', models.BooleanField(default=True)),
                ('date_submitted', models.DateField()),
            ],
        ),
    ]
