# Generated by Django 5.0.6 on 2025-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='max_age_restriction',
            field=models.IntegerField(default=1),
        ),
    ]
